"""Best-effort AI-text detection.

There is no reliable, general-purpose way to prove a text was AI-generated —
every commercial "AI detector" has real false-positive rates, and they are
worst for short texts, non-native English writing, and formal/technical
prose. This service combines two weak, independent signals into a single
estimate and is explicit about that uncertainty in every response (see
``disclaimer`` below) rather than presenting a bare confident percentage.

Signal 1 (heuristic, deterministic, free): sentence-length burstiness,
lexical diversity, and density of overused "AI-tell" phrases. Pure function,
no network call — easy to unit test and always available. This is a SECONDARY
channel: it raises suspicion when positive AI-tells are present, but it is
deliberately NOT allowed to vote "human" just because the prose is clean and
well varied — modern AI produces exactly that, and treating polish as a human
signal is what caused clean AI text to be mislabelled.

Signal 2 (LLM judgment, primary): asks the model for its own probability
estimate plus the sentences it finds most AI-like (used for highlighting).
More semantically aware than the heuristics but can fail (bad JSON, API
error); the result degrades gracefully to heuristic-only if so.
"""

import json
import logging
import re
import statistics

from app.core.exceptions import AppError
from app.services.ai_service import AIService
from app.services.runtime_settings import runtime_settings

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "A strict estimate, not proof — false positives happen, especially on short "
    "or formal text. Don't use this as the sole basis for an accusation."
)

# Phrases disproportionately common in unedited LLM output. Not proof on
# their own — just one weak signal among several.
_AI_TELL_PHRASES = [
    "delve into", "tapestry", "boundaries of", "landscape of", "moreover,",
    "furthermore,", "in conclusion,", "it's important to note", "it is important to note",
    "in today's world", "in the realm of", "navigate the complexities",
    "unlock the potential", "unleash the power", "harness the power",
    "cutting-edge", "seamless", "holistic approach", "paradigm shift",
    "testament to", "ever-evolving", "in summary,", "overall,", "additionally,",
    "consequently,", "notably,", "plays a crucial role", "plays a vital role",
    "as an ai language model", "i cannot browse the internet",
    "it's worth noting", "when it comes to", "a myriad of", "underscores the importance",
    "at the end of the day", "dive deeper", "the ever-changing", "crucial to understand",
]

# Structural constructions (not fixed phrases) disproportionately common in
# unedited LLM output — negative parallelism ("isn't X, it's Y") and vague
# appeals to unnamed authority. Same weak-signal caveat as the phrase list
# above: common enough in genuine human writing that a single hit proves
# nothing, but density across a whole document is corroborating evidence.
_AI_TELL_PATTERNS = [
    re.compile(r"\b(?:is|are|was|were)\s*n[o']t\b[^.?!,]{0,50},\s*it'?s\b", re.IGNORECASE),
    re.compile(r"\bit'?s\s+not\s+[^.?!,]{2,40},\s*it'?s\b", re.IGNORECASE),
    re.compile(r"\bnot\s+(?:just|only)\b[^.?!]{0,60}?\bbut\b", re.IGNORECASE),
    re.compile(r"\b(?:studies show|experts agree|research suggests|industry insiders|it is widely known|it's widely known)\b", re.IGNORECASE),
]

MIN_WORDS_FOR_CONFIDENCE = 60

_LLM_SYSTEM_PROMPT = """You are a strict, decisive AI-text detector. Estimate the probability that \
the given text was generated by an AI language model.

Be decisive. Do not default to a cautious middle-ground number just because you are not 100% \
certain — that is a cop-out, not caution. Commit:
- If the text shows AI-typical patterns (generic transitions, hedge-heavy or listy structure, \
vague-but-confident phrasing, overused stock phrases, an absence of personal voice or concrete \
lived detail), commit to a high probability (0.8+).
- If the text reads like authentic human writing (concrete specifics, irregular rhythm, personal \
voice, opinions, small imperfections, idiosyncrasy), commit to a low probability (0.2 or below).
- Reserve the 0.4-0.6 range ONLY for text that is genuinely ambiguous — not as a default fallback.

Critical: clean grammar, correct spelling, and varied sentence length are NOT evidence of a \
human author. Modern AI produces polished, well-varied prose. Judge voice, specificity, and \
idiosyncrasy — not surface polish.

Also critical: weigh proportion. If only a short aside reads as personal while the surrounding \
majority of the text shows AI-typical patterns, that majority should still decide the score — a \
brief human-sounding line does not override a longer AI-typical passage around it.

In fiction, poetry, marketing, reviews, or any first-person creative writing, personal voice \
alone is NOT proof of a human author — competent AI produces vivid, emotional, first-person prose \
fluently. The real test in these genres is specific vs. generic:
- Human, scored low: "The bus was already pulling away when I saw her, and for one stupid second \
I actually ran, in my work shoes, on the wet part of the platform, holding my bag over my head \
like an idiot, and she didn't even see me, she was looking at her phone the entire time." The \
detail (wet platform, bag over her head, she wasn't even looking) is oddly specific and slightly \
unflattering — the kind of thing one particular person notices about their own memory, not a \
story beat.
- AI, scored high: "As I stood there in the rain, memories flooded back to me, each one a reminder \
of everything we had shared and everything I now stood to lose. I knew, in that moment, that I \
would never forget the way the streetlights reflected in the puddles beneath my feet." Every \
image here (rain, memories flooding back, streetlights in puddles) is a generic, interchangeable \
"emotional moment" beat that could be dropped into any story about loss — nothing is specific to \
one narrator's actual situation.
Ask: does a detail feel like one person's odd, unrepeatable noticing, or could it be swapped into \
any other story about a similar feeling without losing anything? The first is human evidence even \
in fiction or poetry; the second is not, regardless of genre — and this cuts both ways: genuinely \
specific, idiosyncratic personal-voice writing should still score low even when it's clearly \
fiction, poetry, or persuasive copy.

Also copy out, verbatim, the individual sentences from the text that most strongly read as \
AI-written (up to 6, exactly as they appear). If the whole text reads human, return an empty list.

Respond with ONLY a JSON object, no other text: \
{"ai_probability": <float 0.0-1.0>, "reasoning": "<one short, direct sentence>", \
"ai_sentences": ["<verbatim sentence>", ...]}"""


_MIN_PROBABILITY = 0.02
_MAX_PROBABILITY = 0.98

_PARAGRAPH_SYSTEM_PROMPT = """You will receive a text split into numbered segments, each on its \
own line prefixed "[N] ". For EACH segment, independently estimate the probability it was \
AI-generated, using the same strict standard: judge voice, specificity, and idiosyncrasy — not \
surface polish. Commit to decisive numbers; reserve 0.4-0.6 only for a segment that is genuinely, \
evenly ambiguous on its own.

Respond with ONLY a JSON object, no other text: \
{"segments": [{"index": <int>, "ai_probability": <float 0.0-1.0>}, ...]}"""

_MAX_PARAGRAPHS = 12


def _sharpen(probability: float, factor: float = 2.0) -> float:
    """Stretch a probability away from 0.5 so genuinely-close-to-even signals
    still land near 0.5, but anything with real signal in one direction
    commits to a decisive call instead of hedging into "uncertain".

    Clamped short of 0%/100%: this is a heuristic estimate, not proof, and a
    literal 0% or 100% overclaims certainty no detector actually has —
    that's as dishonest as hedging everything into "uncertain" was."""
    stretched = 0.5 + (probability - 0.5) * factor
    return max(_MIN_PROBABILITY, min(_MAX_PROBABILITY, stretched))


def _split_sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]


def compute_heuristics(text: str) -> dict:
    """Pure, deterministic writing-style heuristics. No network calls.

    Rebalanced so the heuristic score behaves as a one-sided "suspicion"
    channel: positive AI-tells (stock phrases, extreme sentence uniformity,
    very low lexical diversity) push the score up, but ordinary well-varied
    prose scores near zero rather than being treated as strong evidence of a
    human author. The old weighting leaned ~65% on burstiness + diversity,
    which let clean, varied AI writing read as "human" — a real false negative.
    """
    words = re.findall(r"[A-Za-z']+", text)
    sentences = _split_sentences(text)
    sentence_lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences if s]

    # Burstiness: coefficient of variation of sentence length. Human writing
    # tends to vary sentence length more; uniform sentence lengths lean AI-ish.
    # Normalized to 0 (very uniform, AI-leaning) - 1 (very bursty, human-leaning).
    if len(sentence_lengths) >= 2 and statistics.mean(sentence_lengths) > 0:
        cv = statistics.pstdev(sentence_lengths) / statistics.mean(sentence_lengths)
        burstiness = min(cv / 0.6, 1.0)  # 0.6 CV ~ typical bursty human writing
    else:
        burstiness = 0.5  # not enough sentences to judge — neutral

    # Lexical diversity: unique words / total words.
    lexical_diversity = len(set(w.lower() for w in words)) / len(words) if words else 0.0

    # AI-tell phrase density, per 100 words.
    lowered = text.lower()
    hits = sum(lowered.count(phrase) for phrase in _AI_TELL_PHRASES)
    hits += sum(len(pattern.findall(text)) for pattern in _AI_TELL_PATTERNS)
    hits_per_100 = (hits / len(words)) * 100 if words else 0.0

    # Combine into a single 0-100 heuristic score (higher = more AI-like).
    # Phrase hits are the strongest, most specific signal and carry the most
    # weight. Uniformity only contributes when sentences are genuinely uniform
    # (burstiness below ~0.45); above that it adds nothing rather than voting
    # "human". Diversity is the noisiest signal and counts least.
    uniformity_score = max(0.0, (0.45 - burstiness) / 0.45) * 100  # only very-uniform text scores
    diversity_score = max(0.0, (0.50 - lexical_diversity)) * 200  # low diversity -> higher score
    phrase_score = min(hits_per_100 * 30, 100)  # phrase hits dominate quickly when present

    heuristic_score = min(
        uniformity_score * 0.30 + diversity_score * 0.15 + phrase_score * 0.55,
        100.0,
    )

    return {
        "burstiness": round(burstiness, 4),
        "lexical_diversity": round(lexical_diversity, 4),
        "ai_phrase_hits": hits,
        "heuristic_score": round(heuristic_score, 2),
        "word_count": len(words),
    }


def _verdict(probability: float) -> str:
    if probability < 0.4:
        return "likely_human"
    if probability > 0.6:
        return "likely_ai"
    return "uncertain"


def _verified_sentences(candidates: list[str], source: str) -> list[str]:
    """Keep only LLM-returned sentences that actually appear in the source text.

    The model is asked for verbatim sentences, but it can paraphrase or
    hallucinate; the frontend highlights by substring match, so anything that
    isn't genuinely present would either fail to highlight or (worse) mislead.
    """
    source_low = source.lower()
    seen: set[str] = set()
    out: list[str] = []
    for candidate in candidates:
        cleaned = candidate.strip()
        key = cleaned.lower()
        if len(cleaned) >= 12 and key in source_low and key not in seen:
            seen.add(key)
            out.append(cleaned)
    return out[:6]


def _split_segments(text: str) -> list[str]:
    """Split into blank-line paragraphs; if the text has none (a single dense
    block), fall back to grouping sentences into ~2-3-sentence chunks so
    Advanced Scan still has multiple segments to break down."""
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    if len(paragraphs) >= 2:
        return paragraphs[:_MAX_PARAGRAPHS]

    sentences = _split_sentences(text)
    if len(sentences) < 4:
        return []  # too short to meaningfully break down

    chunk_size = 2 if len(sentences) <= 10 else 3
    chunks = [
        " ".join(sentences[i : i + chunk_size]).strip()
        for i in range(0, len(sentences), chunk_size)
    ]
    return [c for c in chunks if c][:_MAX_PARAGRAPHS]


class CheckerService:
    def __init__(self, ai_service: AIService):
        self.ai_service = ai_service

    async def _llm_analysis(self, text: str) -> tuple[float | None, str | None, list[str]]:
        """Primary signal: probability + the sentences the model finds most AI-like."""
        try:
            raw = await self.ai_service.classify(
                [("system", _LLM_SYSTEM_PROMPT), ("human", text[:8000])]
            )
            parsed = json.loads(raw.strip().strip("`").removeprefix("json").strip())
            probability = float(parsed["ai_probability"])
            probability = max(0.0, min(1.0, probability))
            reasoning = str(parsed.get("reasoning", ""))[:300]
            raw_sentences = parsed.get("ai_sentences") or []
            candidates = [str(s) for s in raw_sentences if isinstance(s, str)]
            return probability, reasoning, candidates
        except Exception:
            logger.warning("checker_llm_estimate_failed", exc_info=True)
            return None, None, []

    async def _paragraph_breakdown(self, text: str) -> list[dict]:
        """Advanced Scan: score each paragraph/segment independently, rather
        than only the whole text plus a handful of flagged sentences. One
        extra LLM call, only made when the caller asks for it.

        Tried folding a word-count-weighted average of these segment scores
        into the primary probability (so a short human-sounding aside inside
        an AI-majority document couldn't anchor the whole-text read). Reverted:
        live testing showed the per-segment scores themselves are unreliable —
        on one real case the personal, human-sounding sentences scored HIGHER
        AI-probability (0.9, 0.98) than the surrounding generic corporate
        prose (0.1, 0.7), backwards from the intended signal — and repeat
        runs on identical input drifted (0.5-0.98 range across two calls)
        despite the temperature=0 classifier client. Blending an unreliable,
        non-reproducible secondary signal into the primary score risked
        reintroducing the exact repeatability bug fixed earlier in this
        project. Left as a display-only feature for Advanced Scan.
        """
        segments = _split_segments(text)
        if len(segments) < 2:
            return []

        numbered = "\n\n".join(f"[{i + 1}] {seg}" for i, seg in enumerate(segments))
        try:
            raw = await self.ai_service.classify(
                [("system", _PARAGRAPH_SYSTEM_PROMPT), ("human", numbered[:10000])]
            )
            parsed = json.loads(raw.strip().strip("`").removeprefix("json").strip())
            raw_segments = parsed.get("segments") or []
        except Exception:
            logger.warning("checker_paragraph_breakdown_failed", exc_info=True)
            return []

        indexed_out: list[tuple[int, dict]] = []
        for item in raw_segments:
            if not isinstance(item, dict):
                continue
            try:
                idx = int(item.get("index")) - 1
                probability = max(0.0, min(1.0, float(item.get("ai_probability"))))
            except (TypeError, ValueError):
                continue
            if 0 <= idx < len(segments):
                sharpened = _sharpen(probability)
                indexed_out.append(
                    (
                        idx,
                        {
                            "text": segments[idx],
                            "ai_probability": round(sharpened, 4),
                            "verdict": _verdict(sharpened),
                        },
                    )
                )
        indexed_out.sort(key=lambda pair: pair[0])
        return [item for _, item in indexed_out]

    async def check_text(self, text: str, advanced: bool = False) -> dict:
        stripped = text.strip()
        if not stripped:
            raise AppError(code="EMPTY_TEXT", message="Text must not be empty", status_code=400)

        max_chars = int(runtime_settings.get("checker_max_chars"))
        if len(stripped) > max_chars:
            raise AppError(
                code="TEXT_TOO_LONG",
                message=f"Text exceeds the {max_chars}-character limit",
                status_code=413,
            )

        heuristics = compute_heuristics(stripped)
        llm_probability, llm_reasoning, llm_sentences = await self._llm_analysis(stripped)

        heuristic_probability = heuristics["heuristic_score"] / 100.0
        if llm_probability is not None:
            # The LLM is the primary, semantically-aware signal; heuristics
            # corroborate. Weighted 70/30 toward the LLM.
            blended_probability = 0.7 * llm_probability + 0.3 * heuristic_probability
            # Guardrail against the false-negative this rework fixes: when the
            # heuristic looks "human" (clean, varied prose) but the LLM is
            # GENUINELY confident it's AI (>=0.9), do not let the heuristic
            # drag that call back down toward "uncertain". Gated at 0.9 rather
            # than any heuristic<llm gap: an unconditional floor also
            # amplified moderately-confident LLM calls (~0.85, right at the
            # prompt's own "high" threshold, not deep into it) into an
            # overclaimed near-100% number on text the heuristic correctly
            # read as human — found via a real false positive on a genuine,
            # non-native-English academic paper excerpt. Positive AI-tells can
            # still pull the blend up via the weighted average above.
            if heuristic_probability < llm_probability and llm_probability >= 0.9:
                blended_probability = max(blended_probability, llm_probability * 0.9)
        else:
            blended_probability = heuristic_probability
        final_probability = _sharpen(blended_probability)

        confidence = "low" if heuristics["word_count"] < MIN_WORDS_FOR_CONFIDENCE else "moderate"
        ai_sentences = _verified_sentences(llm_sentences, stripped)
        paragraphs = await self._paragraph_breakdown(stripped) if advanced else []

        explanation_parts = []
        if llm_reasoning:
            explanation_parts.append(llm_reasoning)
        if heuristics["ai_phrase_hits"] > 0:
            explanation_parts.append(
                f"Flagged {heuristics['ai_phrase_hits']} phrase(s) overused in AI writing."
            )
        if confidence == "low":
            explanation_parts.append(
                f"Text is short ({heuristics['word_count']} words) — treat this call with extra caution."
            )
        if not explanation_parts:
            explanation_parts.append("Based on sentence-rhythm uniformity and word-choice patterns.")

        return {
            "ai_probability": round(final_probability, 4),
            "verdict": _verdict(final_probability),
            "confidence": confidence,
            "signals": {
                "burstiness": heuristics["burstiness"],
                "lexical_diversity": heuristics["lexical_diversity"],
                "ai_phrase_hits": heuristics["ai_phrase_hits"],
                "heuristic_score": heuristics["heuristic_score"],
                "llm_probability": round(llm_probability, 4) if llm_probability is not None else None,
            },
            "ai_sentences": ai_sentences,
            "paragraphs": paragraphs,
            "explanation": " ".join(explanation_parts),
            "disclaimer": DISCLAIMER,
        }
